name: Cleanup Neon Database Branch
on:
  push:
    branches:
      - 'main'
jobs:
  delete-branch:
    environment: 
      name: development
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Get PR info
        id: get-pr-info
        uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
      - run: |
          echo ${{ steps.get-pr-info.outputs.number}}
      - name: Delete Neon Branch
        if: ${{ steps.get-pr-info.outputs.number }}
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch: pr-${{ steps.get-pr-info.outputs.number }}
          api_key: ${{ secrets.NEON_API_KEY }}
