name: Deploy Platformatic application to the cloud
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: 
      name: development
    steps:
      - name: Checkout application project repository
        uses: actions/checkout@v3
      - name: npm install --omit=dev
        run: npm install --omit=dev
      - name: Get PR number
        id: get_pull_number
        run: |
          pull_sha=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH")
          echo "pull_sha=${pull_sha}" >> $GITHUB_OUTPUT
          echo $pull_sha
      - uses: neondatabase/delete-branch-by-name-action.yml@main
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{ steps.get_pull_number.outputs.pull_sha }}
          api_key: {{ secrets.NEON_API_KEY }}
      - uses: neondatabase/create-branch-action@v2
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{ steps.get_pull_number.outputs.pull_sha }}
          api_key: ${{ secrets.NEON_API_KEY }}
          username: ${{secrets.DBUSER}}
          Password: ${{secrets.DBPASSWORD}}       
        id: create-branch
      - name: Get DATABASE_URL
        run: echo DATABASE_URL=${{ steps.create-branch.outputs.db_url}}/neondb
      - name: Deploy project
        uses: platformatic/onestep@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_api_key: ${{ secrets.PLATFORMATIC_API_KEY }}
          platformatic_config_path: ./platformatic.db.json
        env:
          PLT_SERVER_LOGGER_LEVEL: info 
          PORT: 3042 
          PLT_SERVER_HOSTNAME: 127.0.0.1 
          PLT_ADMIN_SECRET: ${{ secrets.PLT_ADMIN_SECRET }}
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url}}/neondb
