name: Deploy Platformatic application to the cloud
on:
  push:
    branches:
      - 'main'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: 
      name: main
    steps:
      - name: Checkout application project repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: npm install --omit=dev
        run: npm install --omit=dev
      - name: Deploy project
        uses: platformatic/onestep@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: ${{ secrets.PLATFORMATIC_STATIC_WORKSPACE_ID }}
          platformatic_workspace_key: ${{ secrets.PLATFORMATIC_STATIC_WORKSPACE_KEY }}
          platformatic_config_path: ./platformatic.db.json
        env:
          PLT_SERVER_LOGGER_LEVEL: info 
          PORT: 3042 
          PLT_SERVER_HOSTNAME: 127.0.0.1 
          PLT_ADMIN_SECRET: ${{ secrets.PLT_ADMIN_SECRET }}
          PLT_LOCK: ${{ vars.PLT_LOCK }}
          PLT_LEADER_POLL: ${{ vars.PLT_LEADER_POLL }}
          DATABASE_URL: ${{ secrets.NEON_DB_URL }}
